---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  LABELS_CONFIG_FILE: '{{.ROOT_DIR}}/labels.yaml'

x-preconditions:
  - &force
    sh: '[[ -z {{.CLI_FORCE}} ]]'
  - &not-root
    sh: '[[ $LOGNAME != "root" ]]'

tasks:

  append-app-labels:
    desc: Append container labels to the labels config file
    cmds:
      - for: { var: apps }
        cmd: |
          yq --inplace '. += [{"name": "app/{{.ITEM}}", "color": "0e8a16"}]' {{.LABELS_CONFIG_FILE}}
    vars:
      apps:
        sh: ls --directory {{.ROOT_DIR}}/../apps/*/ | xargs --max-args=1 basename
    preconditions:
      - *force
      - *not-root
