---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  LABELS_CONFIG_FILE: '{{.ROOT_DIR}}/labels.yaml'

x-preconditions:
  - &not-root
    msg: must not be run as root
    sh: '[[ $LOGNAME != "root" ]]'
  - &gh-workflow
    msg: must only be ran in a GH workflow
    sh: '[[ -z {{.CLI_FORCE}} ]]'

tasks:

  append-app-labels:
    desc: Append container labels to the labels config file
    cmds:
      - for: { var: apps }
        cmd: |
          yq -i '. += [{"name": "app/{{.ITEM}}", "color": "0e8a16"}]' {{.LABELS_CONFIG_FILE}}
    vars:
      apps:
        sh: for dir in {{.ROOT_DIR}}/../apps/*/; do basename "${dir}"; done
    preconditions:
      - *not-root
      - *gh-workflow
