---
creation_rules:
  - # Encrypt .env files
    path_regex: (apps|containers)/.+\.sops\.env
    input_type: dotenv
    key_groups:
      - age:
          - age1dhj7waq642v3tffk0y9yy0wjl853uhxevpggvk5c55g8x66mr4jq2ajq2n
  - # Encrypt .json files
    path_regex: (apps|containers)/.+\.sops\.json
    input_type: json
    key_groups:
      - age:
          - age1dhj7waq642v3tffk0y9yy0wjl853uhxevpggvk5c55g8x66mr4jq2ajq2n
stores:
  yaml:
    indent: 2
