---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

env:
  SOPS_AGE_KEY_FILE: '{{.ROOT_DIR}}/age.key'

includes:
  app:
    taskfile: ./apps
    optional: true

tasks:

  default:
    cmd: task -l
    silent: true

  # https://github.com/coreos/rpm-ostree/issues/2127
  deps:
    desc: Install System Deps
    cmds:
      - sudo rpm-ostree install --idempotent --assumeyes bind-utils expect fastfetch fish fzf gron htop moreutils nano net-tools netcat nmap rsync smartmontools starship systemd-networkd tcpdump telnet tree wget zoxide
      # - sudo rpm-ostree install --idempotent --assumeyes https://downloads.1password.com/linux/rpm/stable/x86_64/1password-cli-latest.x86_64.rpm --uninstall 1password-cli
      - sudo rpm-ostree status -v
      # - sudo systemctl reboot

  start-*:
    desc: Start an app
    cmds:
      - task: reload-{{.APP}}
      - sudo systemctl start {{.APP}}
      - sudo systemctl is-active --quiet {{.APP}} || exit 1
      - sudo podman ps --all --filter name={{.APP}} --format "{{ `{{.Names}} - {{.Image}} - {{.Status}}` }}"
    vars:
      APP: '{{index .MATCH 0}}'

  stop-*:
    desc: Stop an app
    cmd: sudo systemctl stop {{.APP}}
    vars:
      APP: '{{index .MATCH 0}}'
    preconditions:
      - sh: systemctl status {{.APP}}

  restart-*:
    desc: Restart an app
    cmds:
      - task: reload-{{.APP}}
      - sudo systemctl restart {{.APP}}
      - sudo systemctl is-active --quiet {{.APP}} || exit 1
      - sudo podman ps --all --filter name={{.APP}} --format "{{ `{{.Names}} - {{.Image}} - {{.Status}}` }}"
    vars:
      APP: '{{index .MATCH 0}}'
    preconditions:
      - sh: systemctl status {{.APP}}

  status-*:
    desc: Status of an app
    cmd: sudo systemctl status {{.APP}}
    vars:
      APP: '{{index .MATCH 0}}'
    preconditions:
      - sh: systemctl status {{.APP}}

  reload-*:
    desc: Reload an app
    cmds:
      - sudo rsync -rv {{.ROOT_DIR}}/apps/{{.APP}}/{{.APP}}.container /etc/containers/systemd/
      - |
        if test -d {{.ROOT_DIR}}/apps/{{.APP}}/data; then
            sudo rsync -rv --mkpath --delete {{.ROOT_DIR}}/apps/{{.APP}}/data/{{- if eq .CLI_FORCE false }}config/{{ end }} /etc/containers/systemd/{{.APP}}{{- if eq .CLI_FORCE false }}/config{{ end }}
            sudo --preserve-env bash -c "find /etc/containers/systemd/{{.APP}}/config -type f -name "*.sops.*" -print0 | xargs -0 -I {} sops --config {{.ROOT_DIR}}/.sops.yaml --decrypt --in-place {}"
        fi
      - sudo systemctl daemon-reload
    vars:
      APP: '{{index .MATCH 0}}'
    label: reload-{{.APP}}
    sources:
      - '{{.ROOT_DIR}}/apps/{{.APP}}/{{.APP}}.container'
      - '{{.ROOT_DIR}}/apps/{{.APP}}/data/config/**/**'
    generates:
      - /etc/containers/systemd/{{.APP}}.container
      - /etc/containers/systemd/{{.APP}}/config/**/**
      - /run/systemd/generator/{{.APP}}.service
    preconditions:
      - sh: test -f {{.ROOT_DIR}}/apps/{{.APP}}/{{.APP}}.container

  remove-*:
    desc: Remove an app
    prompt: Remove the '{{.APP}}' container ... continue?
    cmds:
      - task: stop-{{.APP}}
      - sudo rm /etc/containers/systemd/{{.APP}}.container
      - sudo rm -rf /etc/containers/systemd/{{.APP}}
      - sudo rm -rf /run/systemd/generator/{{.APP}}.service
      - sudo systemctl daemon-reload
    vars:
      APP: '{{index .MATCH 0}}'

  logs-*:
    desc: Tail logs of a app
    cmd: sudo podman logs -f {{.APP}}
    vars:
      APP: '{{index .MATCH 0}}'
    preconditions:
      - sh: sudo podman inspect {{.APP}}

  list:
    desc: List all apps
    cmd: sudo podman ps --all --format '{{ `{{.Names}}\t{{.Status}}\t{{.Networks}}` }}' --sort names | column -s$'\t' --table

  dotfiles:
    desc: Setup dotfiles
    cmds:
      - | # Nano
        git -C ~/.nano pull || git clone https://github.com/galenguyer/nano-syntax-highlighting ~/.nano
      - | # Fish Hooks
        tee /home/$LOGNAME/.config/fish/conf.d/hooks.fish > /dev/null <<EOF
        mise activate fish | source
        starship init fish | source
        zoxide init fish | source
        EOF
      - | # Fish Greeting
        tee /home/$LOGNAME/.config/fish/conf.d/fish_greeting.fish > /dev/null <<EOF
        function fish_greeting
            fastfetch
        end
        EOF
      - | # Fish Completions
        curl -fsSL -o /home/$LOGNAME/.config/fish/completions/task.fish \
            https://raw.githubusercontent.com/go-task/task/main/completion/fish/task.fish
